name: Setup

runs:
  using: 'composite'

  steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'yarn'

    - name: Install dependencies
      shell: bash
      run: |
        yarn --prefer-offline
