name: Notification
inputs:
  # time:
  #   description: enable/disable show time
  #   required: true
  #   default: disable
  user:
    description: user who active this action
    require: true
  message:
    required: true
runs:
  using: "composite"
  steps:
    - name: Echo
      shell: bash
      run: >-
        echo "
        <a href="https://github.com/${{ inputs.user }}"><strong>@${{ inputs.user }}</strong></a> 
        ${{ inputs.message }} 
        at $(date "+%d/%m/%Y, %H:%M")
        " > pages/notification.md