name: Deploy
inputs:
  message:
    description: message of git commit
    required: true
    default: Publish with NO commit message
  github-token:
    description: serects.GITHUB_TOKEN
    required: true
  ci-token:
    required: true
runs:
  using: "composite"
  steps:
    - name: Commit changes
      shell: bash
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "${{ inputs.message }}" -a
    - name: Git push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ inputs.github-token }}
        branch: ${{ github.ref }}
    - name: Push assets
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ inputs.ci-token }}
      with:
        source-directory: ./assets
        destination-github-username: mem-static
        destination-repository-name: memset0-github-profile
        target-branch: main
        user-email: ci@memset0.cn