name: Deploy
inputs:
  message:
    description: message of git commit
    required: true
    default: Publish with NO commit message
  github-token:
    description: serects.GITHUB_TOKEN
    required: true
runs:
  using: "composite"
  steps:
    - name: Git pull
      shell: bash
      run: |
        git pull
    - name: Configure git
      shell: bash
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
    - name: Commit changes
      shell: bash
      run: |
        git commit -m "${{ inputs.message }}" -a
    - name: Git push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ inputs.github-token }}
        branch: ${{ github.ref }}