name: Tag Cloud Build
runs:
  using: "composite"
  steps:
    # - name: Setup Python
    #   uses: actions/setup-python@v2
    #   with:
    #     python-version: '3.x'
    #     architecture: 'x64'
    # - uses: actions/cache@v1
    #   with:
    #     path: ~/.cache/pip
    #     key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
    #     restore-keys: |
    #       ${{ runner.os }}-pip-
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip' # caching pip dependencies
    - name: Install dependence
      run: |
        pip install -r requirements.txt
    - name: Run python script
      run: |
        python bin/tagcloud
    - name: Purge CDN cache
      run: |
        curl https://purge.jsdelivr.net/gh/memset0/memset0/assets/tagcloud.png
