name: "Build (on push)"
on:
  push:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        uses: ./.github/actions/setup
      - name: Get actor & short SHA
        id: vars
        run: |
          echo "::set-output name=ACTOR ::$GITHUB_ACTOR"
          echo "::set-output name=SHA ::$GITHUB_SHA"
          echo "::set-output name=SHA_SHORT ::$(git rev-parse --short HEAD)"
      - name: Notification
        uses: ./.github/actions/notification
        with:
          user: ${{ steps.vars.outputs.ACTOR }}
          message: >-
            pushed commit
            <a href="https://github.com/memset0/memset0/commit/${{ steps.vars.outputs.SHA }}"><strong><code>${{ steps.vars.outputs.SHA_SHORT }}</code></strong></a>
      - name: Check notification.html
        run: cat pages/notification.md
      - name: Build
        uses: ./.github/actions/build
        with:
          netease-phone: ${{ secrets.NETEASE_PHONE }}
          netease-password: ${{ secrets.NETEASE_PASSWORD }}
      - name: Check README.md
        run: cat README.md
      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          message: Build (By CI)
          github-token: ${{ secrets.GITHUB_TOKEN }}