name: "Build (on push)"
on:
  push:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        uses: ./.github/actions/setup
      - name: Get actor & short SHA
        id: vars
        run: |
          echo "::set-output name=ACTOR ::$GITHUB_ACTOR"
          echo "::set-output name=SHA ::$GITHUB_SHA"
          echo "::set-output name=SHA_SHORT ::$(git rev-parse --short HEAD)"
      - name: Notification
        uses: ./.github/actions/notification
        with:
          # time: enable
          content: >-
            <a href="https://github.com/${{ steps.vars.outputs.ACTOR }}">${{ steps.vars.outputs.ACTOR }}</a>
            committed
            <a href="https://github.com/memset0/memset0/commit/${{ steps.vars.outputs.SHA }}"><code>${{ steps.vars.outputs.SHA_SHORT }}</code></a>
            of this repo
      - name: Check notification.html
        run: cat data/notification.html
      - name: Build
        uses: ./.github/actions/build
        with:
          netease-phone: ${{ secrets.NETEASE_PHONE }}
          netease-password: ${{ secrets.NETEASE_PASSWORD }}
      - name: Check README.md
        run: cat README.md
      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          message: Build
          github-token: ${{ secrets.GITHUB_TOKEN }}