name: "Build (on star)"
on:
  watch:
    types: started
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        uses: ./.github/actions/setup
      - name: Notification
        uses: ./.github/actions/notification
        with:
          user: ${{ github.event.sender.login }}
          message: starred this repo
      - name: Check notification.html
        run: cat pages/notification.md
      - name: Build
        uses: ./.github/actions/build
        with:
          netease-phone: ${{ secrets.NETEASE_PHONE }}
          netease-password: ${{ secrets.NETEASE_PASSWORD }}
      - name: Check README.md
        run: cat README.md
      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          message: Be starred by @${{ github.event.sender.login }}
          github-token: ${{ secrets.GITHUB_TOKEN }}