name: CI (scheduled)
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build
        uses: ./.github/actions/build
        with:
          netease-phone: ${{ secrets.NETEASE_PHONE }}
          netease-password: ${{ secrets.NETEASE_PASSWORD }}
      - name: Check README.md
        run: cat README.md
      - name: Generate tag cloud image
        uses: ./.github/actions/tagcloud
      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          message: Build by CI
          github-token: ${{ secrets.GITHUB_TOKEN }}